log = "info" # possible values: "info", "warn", "trace", "error", "debug"
source_code = "https://github.com/realaravinth/gitpad"
allow_registration = true # allow registration on server
allow_demo = true # allow demo on server
admin_email = "admin@gitpad.example.com"

[server]
# The port at which you want authentication to listen to
# takes a number, choose from 1000-10000 if you dont know what you are doing
port = 7000
#IP address. Enter 0.0.0.0 to listen on all availale addresses
ip= "0.0.0.0" 
# enter your hostname, eg: example.com
domain = "localhost"
proxy_has_tls = false
cookie_secret = "k&y8G#J&2gesW&N6hNauy63vgRzq9ZLPb39"
#workers = 2

[database]
# This section deals with the database location and how to access it
# Please note that at the moment, we have support for only postgresqa.
# Example, if you are Batman, your config would be:
# hostname = "batcave.org"
# port = "5432"
# username = "batman"
# password = "somereallycomplicatedBatmanpassword"
hostname = "localhost"
port = "5432"
username = "postgres"
password = "password"
name = "postgres"
pool = 4
database_type = "postgres"


[repository]
root = "/tmp/gitpad.batsense.net"
